version: '3'
services:

  litecoin:
    build:
      context: .
      dockerfile: Dockerfile.litecoin.dev
    env_file:
      - ~/.env
    volumes:
      - ~/.litecoin:/data/.litecoin
    ports:
      - "9332:9332"
      - "9333:9333"

