version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ~/.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "3000:3000"

  litecoin:
    build:
      context: .
      dockerfile: Dockerfile.litecoin.dev
    env_file:
      - .env
    volumes:
      - .litecoin:/root/.litecoin
    ports:
      - "9332:9332"
      - "9333:9333"

