version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "3000:3000"

  ipfs_host:
    image: ipfs/go-ipfs:latest
    name: ipfs_host
    volumes:
      - /home/dockeruser/nodeupload/uploads:/export
      - /home/dockeruser/data:/data/ipfs
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    restart: always
    environment:
      - IPFS_PROFILE=server


